DROP TABLE IF EXISTS Siswa;
DROP TABLE IF EXISTS Absen;
DROP TABLE IF EXISTS informasi_gambar;
DROP TABLE IF EXISTS Guru;
DROP TABLE IF EXISTS Admin;


CREATE TABLE Siswa (
NIS CHAR(10) NOT NULL PRIMARY KEY,
Nama VARCHAR(50) NOT NULL,
Tanggal_lahir DATE NOT NULL,
Tempat_lahir VARCHAR(100) NOT NULL,
Alamat TEXT NOT NULL,
Jenis_kelamin ENUM ("l","p") NOT NULL,
Agama VARCHAR(50) NOT NULL,
Kelas VARCHAR(10) NOT NULL,
Foto TEXT NOT NULL,
Username VARCHAR(50) NOT NULL,
Password VARCHAR(50) NOT NULL);

CREATE TABLE Absen (
No_absen INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
NIS CHAR(10) NOT NULL,
NIK CHAR(16) NOT NULL,
Tanggal_absen DATE NOT NULL,
Jam_absen TIME NOT NULL,
Kelas_absen VARCHAR(10) NOT NULL,
Info_gambar VARCHAR(10) NOT NULL);

CREATE TABLE informasi_gambar (
Info_gambar VARCHAR(10) NOT NULL PRIMARY KEY,
Tanggal_info DATE NOT NULL,
Jam_info TIME NOT NULL,
Lokasi_info TEXT NOT NULL,
Path TEXT NOT NULL);

CREATE TABLE Guru (
NIK CHAR(16) NOT NULL PRIMARY KEY,
Nama VARCHAR(50) NOT NULL,
Tanggal_lahir DATE NOT NULL,
Tempat_lahir VARCHAR(50) NOT NULL,
Alamat TEXT NOT NULL,
Jenis_kelamin ENUM ("l","p") NOT NULL,
Agama VARCHAR(50) NOT NULL,
Foto TEXT NOT NULL,
Username VARCHAR(50) NOT NULL,
Password VARCHAR(50) NOT NULL);

CREATE TABLE Admin (
NIK CHAR(16) NOT NULL PRIMARY KEY,
Nama VARCHAR(50) NOT NULL,
Tanggal_lahir DATE NOT NULL,
Tempat_lahir VARCHAR(50) NOT NULL,
Alamat TEXT NOT NULL,
Jenis_kelamin ENUM ("l","p") NOT NULL,
Agama VARCHAR(50) NOT NULL,
Foto TEXT NOT NULL,
Username VARCHAR(50) NOT NULL,
Password VARCHAR(50) NOT NULL);

ALTER TABLE Absen ADD CONSTRAINT Absen_NIS_Siswa_NIS FOREIGN KEY (NIS) REFERENCES Siswa(NIS);
ALTER TABLE Absen ADD CONSTRAINT Absen_NIK_Guru_NIK FOREIGN KEY (NIK) REFERENCES Guru(NIK);
ALTER TABLE Absen ADD CONSTRAINT Absen_Info_gambar_informasi_gambar_Info_gambar FOREIGN KEY (Info_gambar) REFERENCES informasi_gambar(Info_gambar);
